exclude:
  - vendor
  - README.md

title: 'Mot√Ωli'
# encode: http://wbwip.com/wbw/emailencoder.html
email: '&#109;&#111;&#116;&#121;&#108;&#105;&#064;&#107;&#114;&#097;&#109;&#111;&#108;&#105;&#115;&#046;&#099;&#122;'
